update query resolved along with seperation of redirect code.
guptakvgaurav/LogDTA pull request #1
Opened 2017-07-27 06:15 UTC by sourabh-khera

2017-07-27 06:52 UTC, guptakvgaurav commented on .gitignore
>  client/bower_components
.idea folder missing...

2017-07-27 06:52 UTC, guptakvgaurav commented on server/api/employee/employee.controller.js
> +import User from './employee.model';
Rename User to Employee to maintain consistency.

2017-07-27 06:52 UTC, guptakvgaurav commented on server/app.js
> +app.use(cookieParser());
All middlewares are registered in express.js file. This is not right place to register middlewares

2017-07-27 06:52 UTC, guptakvgaurav commented on server/components/auth/redirectUrl.js
> +      console.log('Employee -->', employee);
Remove log statement

2017-07-27 06:52 UTC, guptakvgaurav commented on server/components/auth/redirectUrl.js
> +      console.log('Employee -->', employee);
Check other such instances as well

2017-07-27 06:52 UTC, guptakvgaurav commented on server/components/auth/redirectUrl.js
> +      EmployeeSchema.update({
Should be a promise.

2017-07-27 06:52 UTC, guptakvgaurav commented on server/config/seed.js
>  const dummyUsers = [];
Change to dummyEmployees

2017-07-27 06:52 UTC, guptakvgaurav commented on server/routes.js
> +      res.clearCookie('Tsms').send("logout successfull");
Auth.js should have logic for login and logout.

Since, clearing cookie is part of logout, so it belongs to auth.js

2017-07-27 06:52 UTC, guptakvgaurav commented on server/routes.js
> +  app.use(authMiddlewares);
Shouldn't authMiddleware be applicable to all apis. If yes, then why it is placed after user apis

2017-07-27 06:52 UTC, guptakvgaurav commented on server/routes.js
> +    .get((req, res) => {
Can be re-written in cleaner way:

app.route("/api/oauthServerCallback").get(redirectUrlFunction);
Or
app.get("/api/oauthServerCallback", redirectUrlFunction);

2017-07-27 10:27 UTC, sourabh-khera commented on server/components/auth/redirectUrl.js
> +      EmployeeSchema.update({
sir not able to understand this one

2017-07-27 10:27 UTC, sourabh-khera commented on server/components/auth/redirectUrl.js
> +      EmployeeSchema.update({
everything else has been done , so should i push that part

2017-07-27 12:16 UTC, guptakvgaurav requested changes

2017-07-27 12:16 UTC, guptakvgaurav commented on server/components/auth/index.js
> +    res.redirect("http://newers-world-oauth.qa2.tothenew.net/oauth/authorize?client_id=e6d6a83e-6c7a-11e7-9394-406186be844b")
Url should be a constant.

2017-07-27 12:16 UTC, guptakvgaurav commented on server/components/auth/logout.js
> +    res.clearCookie('Tsms').send("logout successful");
Cookie name should be a constant.

2017-07-27 12:16 UTC, guptakvgaurav commented on server/components/auth/redirectUrl.js
> +const EmployeeSchema = require("../../api/employee/employee.model");
Use import instead of require

2017-07-27 12:16 UTC, guptakvgaurav commented on server/components/auth/redirectUrl.js
> +  Network({url: "http://newers-world-oauth.qa2.tothenew.net/oauth/user?access_token=" + hrmsToken, method: 'GET'})
Should be constant.
use string literals instead of + for concatenation.

2017-07-27 12:16 UTC, guptakvgaurav commented on server/components/auth/redirectUrl.js
> +        process.env.SECRET_KEY = 'NothingIsImpossible';
Bad assignment.
SECRET_KEY either should come from process.env or have default value.
const SECRET_KEY = process.env.SECRET_KEY || 'default key value';

2017-07-27 12:16 UTC, guptakvgaurav commented on server/components/auth/redirectUrl.js
> +          maxAge: 900000,
Should be a constant and be part of configuration -> config/environment/

2017-07-27 12:16 UTC, guptakvgaurav commented on server/components/auth/redirectUrl.js
> +          maxAge: 900000,
Same as above

2017-07-27 12:16 UTC, guptakvgaurav commented on server/routes.js
> +const authMiddlewares=require("./components/auth");
use import

2017-07-27 12:16 UTC, guptakvgaurav commented on server/components/auth/logout.js
> +const logout=(req,res)=>{
Add documentation for function:
/**
* <Purpose of function>
* @params - <parameters>
* @return - <return object>
*/

2017-07-27 12:16 UTC, guptakvgaurav commented on server/components/auth/index.js
> +const authChecker = (req, res, next) => {
Add documentation for function:
/**
* <Purpose of function>
* @params - <parameters>
* @return - <return object>
*/

2017-07-27 12:16 UTC, guptakvgaurav commented on server/components/auth/index.js
> +const verifyTsmsToken = (req, res, next) => {
Add documentation for function:
/**
* <Purpose of function>
* @params - <parameters>
* @return - <return object>
*/

2017-07-28 09:48 UTC, guptakvgaurav approved these changes

2017-07-28 09:48 UTC, merged